# Generated by Django 3.0.9 on 2020-08-19 04:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200819_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactssettings',
            name='contacts',
            field=wagtail.core.fields.StreamField([('contact', wagtail.core.blocks.StructBlock([('location', wagtail.core.blocks.CharBlock(help_text='Add country', required=False)), ('address', wagtail.core.blocks.CharBlock(help_text='Add address', required=False)), ('phone', wagtail.core.blocks.CharBlock(help_text='Add phone', required=False)), ('email', wagtail.core.blocks.CharBlock(help_text='Add email', required=False))]))]),
        ),
    ]
