# Generated by Django 3.0.9 on 2020-08-24 09:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('common', '0005_privacypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', wagtail.core.fields.StreamField([('contact', wagtail.core.blocks.StructBlock([('location', wagtail.core.blocks.CharBlock(help_text='Add country', required=False)), ('address', wagtail.core.blocks.CharBlock(help_text='Add address', required=False)), ('phone', wagtail.core.blocks.CharBlock(help_text='Add phone', required=False)), ('email', wagtail.core.blocks.CharBlock(help_text='Add email', required=False))]))])),
                ('email', models.CharField(help_text='Add email', max_length=60)),
                ('privacy_text', wagtail.core.fields.RichTextField(blank=True, help_text='Privacy text', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContactsSettings',
        ),
    ]
