# Generated by Django 3.0.9 on 2020-10-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('common', '0006_auto_20200824_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='watermark_background',
            field=models.ForeignKey(blank=True, help_text='Watermark backgroud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='watermark_logo',
            field=models.ForeignKey(blank=True, help_text='Watermark logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
