# Generated by Django 3.0.8 on 2020-08-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('portfolio', '0005_auto_20200807_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('projects', wagtail.core.fields.StreamField([('game', wagtail.core.blocks.StructBlock([('project_page', wagtail.core.blocks.PageChooserBlock(required=True))])), ('animation', wagtail.core.blocks.StructBlock([('video', wagtail.documents.blocks.DocumentChooserBlock(required=True))])), ('drawing', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('sketch', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='DrawgingProjectPage',
            new_name='DrawingProjectPage',
        ),
    ]
