# Generated by Django 3.0.8 on 2020-08-07 10:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200807_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfoliopage',
            name='projects',
            field=wagtail.core.fields.StreamField([('game', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=True)), ('project_page', wagtail.core.blocks.PageChooserBlock(required=True))])), ('animation', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=True)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=True))])), ('drawing', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('sketch', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))]),
        ),
    ]
