# Generated by Django 3.0.8 on 2020-08-07 10:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200807_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfoliopage',
            name='projects',
            field=wagtail.core.fields.StreamField([('page_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=False)), ('project_page', wagtail.core.blocks.PageChooserBlock(required=True))])), ('image_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('video_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(required=False)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))]),
        ),
    ]
