# Generated by Django 3.0.8 on 2020-08-07 12:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('portfolio', '0009_auto_20200807_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('cover', models.ForeignKey(blank=True, help_text='Ad cover', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('video', models.ForeignKey(blank=True, help_text='Ad video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='drawingprojectpage',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='drawingprojectpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drawingprojectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='gameprojectgalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gameprojectgalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='gameprojectpage',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='gameprojectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='gameprojectpage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='sketchprojectpage',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='sketchprojectpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sketchprojectpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AnimationProjectPage',
        ),
        migrations.DeleteModel(
            name='DrawingProjectPage',
        ),
        migrations.DeleteModel(
            name='GameProjectGalleryImage',
        ),
        migrations.DeleteModel(
            name='GameProjectPage',
        ),
        migrations.DeleteModel(
            name='SketchProjectPage',
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.ProjectPage'),
        ),
    ]
