# Generated by Django 3.0.8 on 2020-08-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('portfolio', '0010_auto_20200807_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgalleryimage',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
