# Generated by Django 3.0.9 on 2020-08-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('portfolio', '0011_projectgalleryimage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
