# Generated by Django 3.0.9 on 2020-08-24 09:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('portfolio', '0012_auto_20200822_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfoliopage',
            name='projects',
            field=wagtail.core.fields.StreamField([('page_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(help_text='The image sould be about 300x500 size', required=False)), ('project_page', wagtail.core.blocks.PageChooserBlock(required=True))])), ('image_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(help_text='The image sould be about 300x500 size', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('video_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(help_text='The image sould be about 300x500 size', required=False)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))]),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='The image sould be about 300x500 size', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
