# Generated by Django 3.0.9 on 2020-09-07 01:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200824_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfoliopage',
            name='projects',
            field=wagtail.core.fields.StreamField([('page_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(help_text='The image sould be about 300x500 size', required=False)), ('project_page', wagtail.core.blocks.PageChooserBlock(required=True))])), ('image_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(help_text='The image sould be about 300x500 size', required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('video_block', wagtail.core.blocks.StructBlock([('cover', wagtail.images.blocks.ImageChooserBlock(help_text='The image sould be about 300x500 size', required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('video', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))]),
        ),
    ]
