# Generated by Django 3.0.9 on 2020-09-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('portfolio', '0014_auto_20200907_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgalleryimage',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
